#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2016

/usr/bin/openskyd-dump1090 2>&1 | \
    stdbuf -oL awk '{print "[" strftime("%Y/%m/%d %H:%M:%S", systime()) "][opensky-feeder] " $0}'
